### ISSUE TITLE
프로젝트 마무리 전까지 해야할 일

### ISSUE THREAD

**Issue by CocoIsCat** [spring-project-team1/naverpay-clone-project#19]
# 로그인 구현
- [x] 로그인 실패 시 500번 에러 뜨는 거 수정하기
- 다시 로그인 페이지로 이동하게 하면 될 거 같음

# 상품 리스트 보기
- [x] 기간 검색 기능 추가하기

# 상품 상세 정보 보기
- [x] 띄어쓰기 언더바 수정
- 가능하다면...

**Comment by WONSEOKJE** [comment]
로그인 실패 시 500번 에러 뜨는 거 수정 완료 했습니다
